In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('/content/Fraudulent_E-Commerce_Transaction_Data_2.csv')

In [3]:
df.shape

(23634, 16)

In [4]:
df.head()

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour
0,c12e07a0-8a06-4c0d-b5cc-04f3af688570,8ca9f102-02a4-4207-ab63-484e83a1bdf0,42.32,2024-03-24 23:42:43,PayPal,electronics,1,40,East Jameshaven,desktop,110.87.246.85,5399 Rachel Stravenue Suite 718\nNorth Blakebu...,5399 Rachel Stravenue Suite 718\nNorth Blakebu...,0,282,23
1,7d187603-7961-4fce-9827-9698e2b6a201,4d158416-caae-4b09-bd5b-15235deb9129,301.34,2024-01-22 00:53:31,credit card,electronics,3,35,Kingstad,tablet,14.73.104.153,"5230 Stephanie Forge\nCollinsbury, PR 81853","5230 Stephanie Forge\nCollinsbury, PR 81853",0,223,0
2,f2c14f9d-92df-4aaf-8931-ceaf4e63ed72,ccae47b8-75c7-4f5a-aa9e-957deced2137,340.32,2024-01-22 08:06:03,debit card,toys & games,5,29,North Ryan,desktop,67.58.94.93,"195 Cole Oval\nPort Larry, IA 58422","4772 David Stravenue Apt. 447\nVelasquezside, ...",0,360,8
3,e9949bfa-194d-486b-84da-9565fca9e5ce,b04960c0-aeee-4907-b1cd-4819016adcef,95.77,2024-01-16 20:34:53,credit card,electronics,5,45,Kaylaville,mobile,202.122.126.216,"7609 Cynthia Square\nWest Brenda, NV 23016","7609 Cynthia Square\nWest Brenda, NV 23016",0,325,20
4,7362837c-7538-434e-8731-0df713f5f26d,de9d6351-b3a7-4bc7-9a55-8f013eb66928,77.45,2024-01-16 15:47:23,credit card,clothing,5,42,North Edwardborough,desktop,96.77.232.76,"2494 Robert Ramp Suite 313\nRobinsonport, AS 5...","2494 Robert Ramp Suite 313\nRobinsonport, AS 5...",0,116,15

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23634 entries, 0 to 23633
Data columns (total 16 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Transaction ID      23634 non-null  object
 1   Customer ID         23634 non-null  object
 2   Transaction Amount  23634 non-null  float64
 3   Transaction Date    23634 non-null  object
 4   Payment Method      23634 non-null  object
 5   Product Category    23634 non-null  object
 6   Quantity            23634 non-null  int64
 7   Customer Age        23634 non-null  int64
 8   Customer Location   23634 non-null  object
 9   Device Used         23634 non-null  object
 10  IP Address          23634 non-null  object
 11  Shipping Address    23634 non-null  object
 12  Billing Address     23634 non-null  object
 13  Is Fraudulent       23634 non-null  int64
 14  Account Age Days    23634 non-null  int64
 15  Transaction Hour    23634 non-null  int64
dtypes: float64(1), int64(5), object(10)
memory usage: 2.9+ MB

In [6]:
df.isna().sum()

Transaction ID        0
Customer ID           0
Transaction Amount    0
Transaction Date      0
Payment Method        0
Product Category      0
Quantity              0
Customer Age          0
Customer Location     0
Device Used           0
IP Address            0
Shipping Address      0
Billing Address       0
Is Fraudulent         0
Account Age Days      0
Transaction Hour      0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
object_columns = df.select_dtypes(include=['object']).columns

In [9]:
for col in object_columns:

    df[col] = df[col].astype(str).str.strip()

    df[col] = df[col].str.lower()

In [10]:
df['Transaction Date'] = pd.to_datetime(df['Transaction Date'])

In [11]:
df['Transaction Date']

0       2024-03-24 23:42:43
1       2024-01-22 00:53:31
2       2024-01-22 08:06:03
3       2024-01-16 20:34:53
4       2024-01-16 15:47:23
                ...
23629   2024-01-26 16:25:05
23630   2024-02-25 17:03:26
23631   2024-03-28 23:46:47
23632   2024-02-09 11:29:18
23633   2024-01-23 02:46:52
Name: Transaction Date, Length: 23634, dtype: datetime64[ns]

In [12]:
df['Day of Week'] = df['Transaction Date'].dt.day_name()

In [13]:
df['Day of Week']

0          Sunday
1          Monday
2          Monday
3         Tuesday
4         Tuesday
           ...
23629      Friday
23630      Sunday
23631    Thursday
23632      Friday
23633     Tuesday
Name: Day of Week, Length: 23634, dtype: object

In [14]:
df['Month'] = df['Transaction Date'].dt.month_name()

In [15]:
def categorize_hour(hour):
    if 0 <= hour < 6:
        return 'Late Night'
    elif 6 <= hour < 12:
        return 'Morning'
    elif 12 <= hour < 18:
        return 'Afternoon'
    else:
        return 'Evening'

In [16]:
df['Time Segment'] = df['Transaction Hour'].apply(categorize_hour)

In [17]:
df['Time Segment']

0           Evening
1        Late Night
2           Morning
3           Evening
4         Afternoon
            ...
23629     Afternoon
23630     Afternoon
23631       Evening
23632       Morning
23633    Late Night
Name: Time Segment, Length: 23634, dtype: object

In [18]:
invalid_amounts = df[df['Transaction Amount'] <= 0]

In [19]:
invalid_amounts

Empty DataFrame
Columns: [Transaction ID, Customer ID, Transaction Amount, Transaction Date, Payment Method, Product Category, Quantity, Customer Age, Customer Location, Device Used, IP Address, Shipping Address, Billing Address, Is Fraudulent, Account Age Days, Transaction Hour, Day of Week, Month, Time Segment]
Index: []

In [ ]:
df.head()

,Transaction ID,Customer ID,Transaction Amount,Transaction Date,Payment Method,Product Category,Quantity,Customer Age,Customer Location,Device Used,IP Address,Shipping Address,Billing Address,Is Fraudulent,Account Age Days,Transaction Hour,Day of Week,Month,Time Segment
0,c12e07a0-8a06-4c0d-b5cc-04f3af688570,8ca9f102-02a4-4207-ab63-484e83a1bdf0,42.32,2024-03-24 23:42:43,paypal,electronics,1,40,east jameshaven,desktop,110.87.246.85,5399 rachel stravenue suite 718\nnorth blakebu...,5399 rachel stravenue suite 718\nnorth blakebu...,0,282,23,Sunday,March,Evening
1,7d187603-7961-4fce-9827-9698e2b6a201,4d158416-caae-4b09-bd5b-15235deb9129,301.34,2024-01-22 00:53:31,credit card,electronics,3,35,kingstad,tablet,14.73.104.153,"5230 stephanie forge\ncollinsbury, pr 81853","5230 stephanie forge\ncollinsbury, pr 81853",0,223,0,Monday,January,Late Night
2,f2c14f9d-92df-4aaf-8931-ceaf4e63ed72,ccae47b8-75c7-4f5a-aa9e-957deced2137,340.32,2024-01-22 08:06:03,debit card,toys & games,5,29,north ryan,desktop,67.58.94.93,"195 cole oval\nport larry, ia 58422","4772 david stravenue apt. 447\nvelasquezside, ...",0,360,8,Monday,January,Morning
3,e9949bfa-194d-486b-84da-9565fca9e5ce,b04960c0-aeee-4907-b1cd-4819016adcef,95.77,2024-01-16 20:34:53,credit card,electronics,5,45,kaylaville,mobile,202.122.126.216,"7609 cynthia square\nwest brenda, nv 23016","7609 cynthia square\nwest brenda, nv 23016",0,325,20,Tuesday,January,Evening
4,7362837c-7538-434e-8731-0df713f5f26d,de9d6351-b3a7-4bc7-9a55-8f013eb66928,77.45,2024-01-16 15:47:23,credit card,clothing,5,42,north edwardborough,desktop,96.77.232.76,"2494 robert ramp suite 313\nrobinsonport, as 5...","2494 robert ramp suite 313\nrobinsonport, as 5...",0,116,15,Tuesday,January,Afternoon

In [ ]:
avg=df["Customer Age"].mean()

In [ ]:
avg

np.float64(34.56020986714056)

In [ ]:

df.to_csv("/content/Fraudulent_E-Commerce_clean.csv")